using Firmeza.Data.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Linq;

namespace Firmeza.Services
{
    // IDocument es la interfaz principal para la generación de PDFs
    public class ReceiptDocument : IDocument
    {
        public Receipt Receipt { get; }
        public ReceiptDocument(Receipt receipt)
        {
            Receipt = receipt;
        }
        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
        public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Margin(30);
                    page.Header().Element(ComposeHeader);
                    page.Content().Element(ComposeContent);
                    page.Footer().Element(ComposeFooter);
                });
        }
        void ComposeHeader(IContainer container)
        {
            container.Row(row =>
            {
                // Título principal
                row.RelativeColumn(3).Text("FIRMEZA E-COMMERCE RECEIPT")
                    .SemiBold().FontSize(18).FontColor(Colors.Blue.Medium);

                // Información del recibo
                row.RelativeColumn(2).AlignRight().Column(column =>
                {
                    column.Item().Text($"RECEIPT ID: #{Receipt.Id}").SemiBold().FontSize(12);
                    column.Item().Text($"Date: {Receipt.ReceiptDate:yyyy-MM-dd HH:mm}").FontSize(10);
                });
            });
        }

        // --- Contenido Principal (Detalle de Ítems) ---
        void ComposeContent(IContainer container)
        {
            container.PaddingVertical(10).Column(column =>
            {
                // 1. Información del Cliente
                column.Item().PaddingBottom(10).Text(text =>
                {
                    text.Span("Client: ").SemiBold().FontSize(11);
                    text.Span($"{Receipt.Client.FullName} | {Receipt.Client.Email}").FontSize(11);
                });

                // Separador
                column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                // 2. Tabla de Ítems
                column.Item().Table(table =>
                {
                    // Definición de Columnas (Ancho Relativo)
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(5); 
                        columns.ConstantColumn(60); 
                        columns.ConstantColumn(80); 
                        columns.ConstantColumn(80); 
                    });

                    // Encabezado de la Tabla
                    table.Header(header =>
                    {
                        header.Cell().Element(BlockHeader).Text("Product");
                        header.Cell().Element(BlockHeader).AlignRight().Text("Qty");
                        header.Cell().Element(BlockHeader).AlignRight().Text("Unit Price");
                        header.Cell().Element(BlockHeader).AlignRight().Text("Net Total");

                        static IContainer BlockHeader(IContainer x) => x.PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Grey.Medium);
                    });

                    // Filas de la Tabla
                    foreach (var line in Receipt.SaleLines)
                    {
                        table.Cell().PaddingVertical(3).Text(line.Product.Name);
                        table.Cell().AlignRight().Text(line.Quantity.ToString());
                        table.Cell().AlignRight().Text(line.PricePerUnit.ToString("C"));
                        table.Cell().AlignRight().Text(line.NetTotal.ToString("C"));
                    }
                });

                // 3. Resumen de Totales
                var netTotal = Receipt.GrossTotal - Receipt.IvaTotal;

                column.Item().PaddingTop(15).AlignRight().Column(totals =>
                {
                    totals.Item().Text($"Subtotal (Net): {netTotal.ToString("C")}").FontSize(11);
                    totals.Item().Text($"IVA Total: {Receipt.IvaTotal.ToString("C")}").FontSize(11);
                    
                    totals.Item().PaddingTop(5).Text($"GROSS TOTAL: {Receipt.GrossTotal.ToString("C")}")
                        .FontSize(14).SemiBold().FontColor(Colors.Green.Darken1).BackgroundColor(Colors.Green.Lighten5).BackgroundColor(5);
                });
            });
        }

        // --- Pie de Página ---
        void ComposeFooter(IContainer container)
        {
            container.PaddingTop(10).AlignCenter().Text(text =>
            {
                text.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Grey.Darken1));
                text.Span("Generated by Firmeza Admin System | Page ").Italic();
                text.CurrentPageNumber();
                text.Span(" of ");
                text.TotalPages();
            });
        }
    }
}